{
 "title": "Anomaly Count Comparison",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Anomalous vs. Nominal Metrics",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(anomalous_record_count_total[$__rate_interval])",
     "legendFormat": "Anomalous Records"
    },
    {
     "expr": "increase(nominal_record_count_total[$__rate_interval])",
     "legendFormat": "Normal Records"
    }
   ]
  },
  {
   "title": "API Request Duration Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_bucket[$__rate_interval])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{http_response_status_code=~\"4..|5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{http_response_status_code=~\"2..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{}[$__rate_interval]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Anomaly Score Distributions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anomaly_score_dist_bucket{le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Trace Records",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "limit": 20,
     "query": "{span.http.request.method!=\"OPTIONS\" && span.http.route!=\"/health\"} >> {} | select(span.is_anomaly)",
     "tableType": "traces"
    }
   ]
  }
 ]
}