receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  cumulativetodelta:
    include:
      metric_types:
        - sum
        - histogram
  batch:

exporters:
  debug:
    verbosity: detailed
  kafka:
    brokers:
      - kafka:9092
    protocol_version: 2.0.0
    encoding: otlp_json


service:
  pipelines:
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [debug, kafka]
    metrics:
      receivers: [otlp]
      processors: [cumulativetodelta]
      exporters: [debug, kafka]