receivers:
  otlp/dotnet:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  otlp/python:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4319
      http:
        endpoint: 0.0.0.0:4320

processors:
  cumulativetodelta:
    include:
      metric_types:
        - sum
        - histogram
  batch:

exporters:
  debug:
    verbosity: detailed
  kafka:
    brokers:
      - kafka:9092
    protocol_version: 2.0.0
    encoding: otlp_json
  prometheus:
    endpoint: "0.0.0.0:9001"
  otlp/tempo:
    endpoint: tempo:4321
    tls:
      insecure: true

service:
  pipelines:
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [debug, kafka]
    metrics/dotnet:
      receivers: [otlp/dotnet]
      processors: [cumulativetodelta]
      exporters: [kafka, prometheus]
    traces/dotnet:
      receivers: [otlp/dotnet]
      exporters: [debug, kafka, otlp/tempo]
    traces/python:
      receivers: [otlp/python]
      exporters: [debug, otlp/tempo]
    metrics/python:
      receivers: [otlp/python]
      processors: [cumulativetodelta]
      exporters: [prometheus]